---
title: "1.변수와 자료형"
author: "Bongus"
date: '2018 6 27 '
output: html_document
---

## 프로그래밍언어로서 R
R이 데이터 분석 도구로 많이 사용되긴 하지만 기본적으로는 하나의 프로그래밍 언어입니다. 그렇기 때문에 R 역시 C, Java, JavaScript, Python과 같은 프로그래밍 언이들과 공통점이 있는데, 바로 **변수, 조건, 반복**의 기능을 갖고 있다는 점입니다. 이번 시간에는 변수에 대해 배워보는 시간을 가져보도록 하겠습니다. 

### 기본 자료형
자료형은 데이터를 식별하는 분류이다. 사용할 데이터가 어떤 종류의 데이터인지 분류하는 것이다. 자료형마다 연산, 사용, 크기에 차이가 있습니다. R에서는 데이터를 정수(integer), 실수(double), 복소수(complex), 문자(character), 논리(logical, TRUE, FALSE)로 분류합니다. 
```{R}
정수 <- 2L #소숫점이 없는 숫자 뒤에 L을 붙여 정수를 표시한다. 기본값은 실수형입니다.,
실수 <-2
복소수 <- 2 + 2i
문자 <- "문자열" # " " or ' ' 안에 사용할 문자를 넣는 형태로 문자열을 사용합니다.
참 <- TRUE # or T
거짓 <- FALSE # or F

typeof(정수)
typeof(실수)
typeof(복소수)
typeof(문자)
typeof(참)
typeof(거짓)
```


### 변수(Variable)
변수를 문자 그대로 해석하면 '변하는 수' 입니다. 프로그래밍 언어에서 변수는 값을 저장하는 저장소의 역할을 합니다. 변수에는 하나의 숫자나 문자 뿐만 아니라 여러개의 숫자나 문자도 하나의 변수에 담을 수 있습니다. R에서 변수는 **<-** 사용해서 만들 수 있습니다. 만들어진 변수를 사용할 때는 **변수명**을 한번 더 입력하고, Window 사용자의 경우 변수명 끝에서 _Ctrl + enter_, Mac 사용자의 경우 _Command + enter_를 눌려주면 변수를 실행할 수 있습니다. 

```{R}
variable1 <- 1
variable1 # in Window Ctrl + enter, in Mac command + enter
variable2 <- "문자"
variable2
variable3 <- c(1,3,"문자") #c() = combine으로 여러 값을 하나로 합쳐줄 때 사용합니다.
variable3
varialbe4 <- 1:5
varialbe4
```
  
변수 사용의 가장 큰 장점은 반복 재사용을 가능하게 해준다는 점입니다. 변수가 없다면 값이 길거나, 큰 값을 사용할 때마다 그 값을 다시 입력해 주어야 합니다. 하지만 값을 변수에 담아놓으면 변수명을 통해 값을 다시 사용할 수 있습니다. 

#### 변수명 생성 규칙
R에서는 변수명을 만들기 위한 몇 가지 규칙이 있습니다. 변수명은 문자로 시작해야합니다. 그리고 중간에 숫자, _, .을 조합해서 만들 수 있습니다. 
  
데이터 분석의 편리함을 위해서 변수명은 직관적이고 통일성을 갖추는 것이 중요합니다. 변수명을 통해 변수 안에 어떤 값을 들어있는지 알 수 있어야하고, 한 데이터 내에서 변수명은 일정한 규칙을 가지고 통일성을 갖추는 것이 좋습니다. 
(한글 변수명도 가능하지만, 권장하는 방법은 아닙니다!)

#### 변수와 연산
뿐만 아니라 변수에 값을 저장해 +, -, x, /, 대소비교(>, <, ==, <=, >=) 같은 연산을 수행할 수 있습니다. 

```{R}
number1 <- 1
number2 <- 2

number1 + number2
number1 + number2
number1 * number2
number1 / number2
number1 > number2
number1 < number2
number1 == number2
```
  
단, 문자는 숫자같은 연산이 불가능합니다. 여러 문자를 하나로 합치기 위해서는 **paste()**라는 함수는 사용하면 됩니다. 함수에 대해서는 추후에 배울 예정입니다.

```{R}
character1 = "문자 1번"
character2 = "문자 2번"
character3 = "문자 3번"
# character1 + character2 오류발생
paste(character1, character2, character3)
``` 
  
여러개의 값으로 구성된 변수 역시 연산이 가능합니다. 
```{R}
variables1 <- 1:5 # 1,2,3,4,5
variables2 <- 6:10 # 6,7,8,9,10
```
여러개의 값으로 구성된 변수에 '3' 같은 하나의 숫자를 더하면, 모든 숫자에 3이 더한 값이 결과로 나타납니다. 그리고 길이 같은 변수끼리 더하면 같은 순서에 위치한 값끼리 연산이 진행됩니다. 

```{R}
variables1 + 3
variables1 + variables2 ## 변수 안의 값들의 개수는 같아야 합니다.
```

### 마무리
지금까지 R의 기본 자료형, 변수에 대해 공부했습니다. 앞으로 내용에서 가장 기본이 되는 내용들이니 꼭 숙지하고 익숙해지도록 합시다. 다음 시간에는 조건문에 대해서 알아보도록 하겠습니다. 
  
  
  ---
  
