---
title: "10.데이터전처리(2)-결측치관리"
author: "Bongus"
date: '2018 8 6 '
output: html_document
---

## 데이터 전처리(2) - 결측치, 이상치 제거하기

### 1. 결측치 제거하기
**결측치(Missing Value)**는 누락된 값, 비어 있는 값을 의미합니다. 현장에서 만들어진 실제 데이터는 수집과정이나 보관과정에서 발생한 오류로 결측치를 포함하고 있을 가능성이 높습니다. 결측치가 있으면 함수가 적용되지 않거나 왜곡된 분석 결과가 나옵니다. 때문에 본격적으로 데이터를 분석하기 전에 결측치가 있는지 확인하고, 결측치를 정제한 후에 데이터를 분석해야 합니다. 

### 1.1 결측치 찾기
결측치를 제거를 위해 임의로 결측치가 들어간 데이터를 만들어 보겠습니다. R에서 결측치는 NA로 표현합니다.  
```{R}
df <- data.frame(sex = c("M", "F", NA, "M", "F"), score = c(5,4,3,4,NA))
df
```
결측치를 확인하기 위해서는 `is.na()`함수를 사용합니다. is.na()함수를 사용하면 결측치를 TRUE, 결측치가 아닌 값을 FALSE로 표시해 결과를 출력합니다. 
```{R}
is.na(df)
```
is.na()를 table()함수에 적용하면 데이터에 결측치가 총 몇개 있는지 출력할 수 있습니다. 
```{R}
table(is.na(df))
```
결측치를 제거하려면 데이터 전체가 아니라 구체적으로 어떤 변수에 결측치가 있는지 알아야 합니다. 
```{R}
table(is.na(df$sex))
table(is.na(df$score))
```
결측치를 포함한 데이터는 함수에 정상적으로 적용되지 않습니다.
```{R}
mean(df$score)
sum(df$score)
```

### 1.2 결측치 제거하기
is.na()에 filter()를 적용하면 결측치가 있는 행을 제거할 수 있습니다. 먼저 결측치가 있는 행만 추출하면...
```{R}
library(dplyr)
df %>% filter(is.na(score))
```
is.na()앞에 **!**을 붙이면 결측치가 아닌 값들이 추출됩니다. 
```{R}
library(dplyr)
df %>% filter(!is.na(score))
```
sex에도 결측치가 포함되어있기 때문에 filter에 &기호를 통해 결측치가 제외된 값들을 뽑아내도록 하겠습니다.
```{R}
library(dplyr)
df %>% filter(!is.na(score) & !is.na(sex))
```
filter함수를 사용하면 일일이 변수를 지정해 결측치가 있는 행을 제거하도록 만든 방법입니다. R에는 na.omit()이라는 함수가 있는데 na.omit()은 NA가 있는 행을 한번에 제거하는 함수입니다. 
```{R}
na.omit(df)
```
결과를 확인하면 filter를 사용해 결측치를 제거한 것과 같은 결과를 얻을 수 있음을 확인할 수 있습니다. 

### 1.3 결측치 제외 기능
mean()과 같은 수치 연산 함수들은 **na.rm**파라미터를 사용해 결측치를 제외하고 연산할 수 있습니다. **na.rm=TRUE**로 설정하고 연산을 하면 결측치를 제외하고 함수를 적용합니다. 하지만 모든 함수가 na.rm을 제공하는 것은 아닙니다. 그럴 경우 filter나 na.omit를 사용해 결측치를 제거하고 연산을 해야합니다. 
```{R}
print(df)
mean(df$score, na.rm = T)
sum(df$score, na.rm = T)
```
summarise()를 이용해 요약 통계량을 산출할 때도 na.rm을 적용할 수 있습니다. 이전에 사용한 `csv_exam.csv`파일에 임의로 NA를 설정해서 사용해보도록 하겠습니다.
```{R}
exam <- read.csv("csv_exam.csv")
exam
exam[c(3,8,15), 'math'] <- NA
exam
```
```{R}
#na.rm 사용전
exam %>% summarise(mean_math = mean(math))
#na.rm 사용후
exam %>% summarise(mean_math = mean(math, na.rm=T))
#여러 데이터에 적용
exam %>% summarise(mean_math = mean(math, na.rm=T),
                   sum_math = sum(math, na.rm=T),
                   median_math = median(math, na.rm=T))
```
### 1.4 결측치 대체하기
데이터가 크고 결측치가 많이 없으면 결측치를 제거하고 분석해도 무리가 없습니다. 하지만 데이터가 작고, 결측치가 많은 경우 결측치가 포함된 데이터 모두를 제거하면 데이터 손실로 결과가 왜곡됩니다. 때문에 데이터가 작고, 결측치가 많으면 결측치를 제거하기보다 다른 값으로 대체하는 방법을 사용하기 도합니다. 대체하는 값은 주로 평균, 최빈값, 중앙값 같은 대표값을 구해 주로 사용합니다. 

```{R}
#이전
exam$math
mean(exam$math, na.rm=T)
#이후
exam$math <- ifelse(is.na(exam$math), mean(exam$math, na.rm=T), exam$math)
table(is.na(exam$math))
exam$math
mean(exam$math)
```
기존에 NA였던 값들이 평균값으로 대체된 것을 확인할 수 있습니다. 평균값 역시 이전에 결측치를 제거하고 구한 평균과 같은 것을 확인할 수 있습니다. 
  
결측치가 있으면 데이터 분석에 오류가 생긴다는 것을 잊으면 안됩니다. 또한 분석할 데이터가 생기면 가장 먼저 결측치를 확인하는 것은 데이터 분석을 하는데 좋은 습관이라고 할 수 있습니다. 
  

### 2. 이상값 제거하기
데이터의 정상 범주에서 크게 벗어난 값을 `이상값(Outlier)`라고 합니다. 데이터의 수집과정에서 오류가 발생할 수 있기 때문에 현장에서 만들어진 실제 데이터에는 이상치가 포함될 수 있습니다. 오류는 아니지만 실제로 극단적인 값이 있을 수도 있습니다. 이상치는 분석 결과를 왜곡하기 때문에 이상치를 제거하는 작업을 해야합니다. 
  
### 2.1 이상값 제거하기 - 존재할 수 없는 값
논리적으로 존재할 수 없는 값이 데이터에 포함되는 경우가 있습니다. 예를들어 남자는 1, 여자는 2로 되어있는 성별변수에 3이라는 숫자가 들어가있는 경우입니다. 이럴 경우 이상값 결측치로 만든 후 제거하고 사용해야 합니다.
```{R}
outlier <- data.frame(sex = c(1,2,1,3,2,1),
                      score = c(5,4,3,4,2,5))
outlier
```
table()함수를 사용하면 빈도표를 통해 데이터를 확인할 수 있습니다. 확인해보면 성별에 3이라는 데이터가 들어가 있음을 확인할 수 있습니다. 3인 데이터를 결측치 처리를 해줍니다.
```{R}
table(outlier$sex)
outlier$sex <- ifelse(outlier$sex == 3, NA, outlier$sex)
outlier
```
이제 결측치를 제거하고, 성별 평균을 구해보도록 하겠습니다.
```{R}
outlier %>% 
  filter(!is.na(sex)) %>% 
  group_by(sex) %>% 
  summarise(mean_scroe = mean(score))
```
남자는 4.33, 여자는 3이 나옴을 확인할 수 있습니다. 
  
### 2.2 이상값 제거하기 - 극단적인 값
논리적으로 존재할 수 있지만 극단적으로 크거나 작은 값을 `극단치`라고 합니다. 예를들어 키가 2m 30cm인 변수가 있다면 존재할 가능성은 있지만 굉장히 드문 경우이기 때문에 극단치라고 할 수 있습니다. 극단치가 있으면 왜곡된 결과가 나올 수 있기 때문에 먼저 제거하고 분석해야 합니다. 이상값 뿐만 아니라 데이터 전체의 특징을 쉽게 파악하기 위해서 박스플롯(boxplot)을 사용합니다. 
  
```{R}
library(ggplot2)
boxplot(mpg$hwy)
```
박스플롯은 데이터를 크기순으로 4등분 했을 때를 기준으로 그린 것입니다. 박스의 경계는 각각 25% 75% 경계를 나타내고, 가운데 검은선은 50%(중앙값)을 나타냅니다. 박스플롯 양 끝에 있는 막대기는 극단치 경계를 나타내고, 그 막대기를 벗어나는 데이터를 극단치(이상값)으로 처리합니다. mpg데이터 셋에있는 hwy값에는 극단치가 있는 것을 확인할 수 있습니다. R에서 boxplot()$stats을 사용하면 해당하는 값들을 확인할 수 있습니다.
```{R}
boxplot(mpg$hwy)$stats
```
hwy데이터는 대부분 12~37 사이에 형성되어있고, 그 범위를 벗어나는 데이터가 극단치로 분류됩니다. 따라서 극단치를 제거하기 위해서는 그 범위를 넘어가는 데이터를 결측치로 만들고, 결측치를 제거하는 방법을 사용하면 됩니다.
```{R}
mpg$hwy <- ifelse(mpg$hwy  < 12 | mpg$hwy  > 37, NA, mpg$hwy)
table(is.na(mpg$hwy))

mpg %>% 
  group_by(drv) %>% 
  summarise(mean_hwy = mean(hwy, na.rm = T))
```

  
이번 시간에는 결측치, 이상값을 처리하는 방법을 알아보았습니다. 결측치, 이상값 모두 데이터 분석을 왜곡하는 요소로 작용하니 반드시 처리하고 데이터를 분석해야 합니다. 처리하는 방법은 유사하니 반드시 숙지하고 넘어가시기 바랍니다. 
  
___
