---
title: "4.기초-함수"
author: "Bongus"
date: '2018 6 28 '
output: html_document
---

## 함수
이번 시간에는 함수에 대해 배울 것입니다. 함수는 특정 연산, 작업 등을 수행하기 위해 만든 기능입니다. 조금 더 쉽게 말하면 **특정한 기능**이 함수입니다. 함수는 R에서 미리 만들어준 함수(내장함수)와 사용자가 함수를 만들어 사용할 수 있습니다. 먼저 함수를 만드는 법과 함수의 구성요소를 배워보도록 하겠습니다.

### 함수만들기

```
1.

함수이름 <- function(arguments...) {
  내용
  return(optional) #return이 없으면 마지막 문장의 반환값을 return
}

arguments(인자)의 개수가 정해지지 않은 경우에는 ...을 통해 인자 개수에 자율성을 부여할 수 있습니다. 

2.

함수이름 <- function(...) {
  내용
  return(optional) #return이 없으면 마지막 문장의 반환값을 return
}
```

```{R}
# 1.
sum1 <- function(num1, num2) {
  number <- num1 + num2
}
print(sum1(1,2))

# 2.
sum2 <- function(...) {
  numbers <- c(...)
  result <-sum(numbers) #숫자를 합하는 함수
}
print(sum2(1,2,3,4,5))
```
  
  
이미 수업들에서 중간중간 함수를 사용했는데, 함수는 `함수명()`의 모습이고, `()`안에 함수에서 요구하는 정보를 넣어 사용하면 됩니다. 어떤 정보가 들어가야되는지 궁금하면 `help(함수명) or ?함수명`을 통해 함수의 정보를 확인할 수 있습니다. 
  
```
?print
help(print)

# 함수정보

Print Values

Description

print prints its argument and returns it invisibly (via invisible(x)). It is a generic function which means that new printing methods can be easily added for new classes.

Usage

print(x, ...)

## S3 method for class 'factor'
print(x, quote = FALSE, max.levels = NULL,
      width = getOption("width"), ...)

## S3 method for class 'table'
print(x, digits = getOption("digits"), quote = FALSE,
      na.print = "", zero.print = "0",
      right = is.numeric(x) || is.complex(x),
      justify = "none", ...)

## S3 method for class 'function'
print(x, useSource = TRUE, ...)
Arguments

x	an object used to select a method.

...	further arguments passed to or from other methods.
quote	logical, indicating whether or not strings should be printed with surrounding quotes.

max.levels integer, indicating how many levels should be printed for a factor; if 0, no extra "Levels" line will be printed. The default, NULL, entails choosing max.levels such that the levels print on one line of width width.

width	only used when max.levels is NULL, see above.

digits	minimal number of significant digits, see print.default.

na.print	character string (or NULL) indicating NA values in printed output, see print.default.

zero.print	character specifying how zeros (0) should be printed; for sparse tables, using "." can produce more readable results, similar to printing sparse matrices in Matrix.

right	logical, indicating whether or not strings should be right aligned.

justify	character indicating if strings should left- or right-justified or left alone, passed to format.

useSource	logical indicating if internally stored source should be used for printing when present, e.g., if options(keep.source = TRUE) has been in use.

Details

The default method, print.default has its own help page. Use methods("print") to get all the methods for the print generic.

print.factor allows some customization and is used for printing ordered factors as well.

print.table for printing tables allows other customization. As of R 3.0.0, it only prints a description in case of a table with 0-extents (this can happen if a classifier has no valid data).

See noquote as an example of a class whose main purpose is a specific print method.

References

Chambers, J. M. and Hastie, T. J. (1992) Statistical Models in S. Wadsworth & Brooks/Cole.

See Also

The default method print.default, and help for the methods above; further options, noquote.

For more customizable (but cumbersome) printing, see cat, format or also write. For a simple prototypical print method, see .print.via.format in package tools.

Examples

require(stats)

ts(1:20)  #-- print is the "Default function" --> print.ts(.) is called
for(i in 1:3) print(1:i)

## Printing of factors
attenu$station ## 117 levels -> 'max.levels' depending on width

## ordered factors: levels  "l1 < l2 < .."
esoph$agegp[1:12]
esoph$alcgp[1:12]

## Printing of sparse (contingency) tables
set.seed(521)
t1 <- round(abs(rt(200, df = 1.8)))
t2 <- round(abs(rt(200, df = 1.4)))
table(t1, t2) # simple
print(table(t1, t2), zero.print = ".") # nicer to read

## same for non-integer "table":
T <- table(t2,t1)
T <- T * (1+round(rlnorm(length(T)))/4)
print(T, zero.print = ".") # quite nicer,
print.table(T[,2:8] * 1e9, digits=3, zero.print = ".")
## still slightly inferior to  Matrix::Matrix(T)  for larger T

## Corner cases with empty extents:
table(1, NA) # < table of extent 1 x 0 >
[Package base version 3.5.0 Index]
```

---

### 내장함수

이제 본격적으로 함수를 사용해보도록 하겠습니다. 앞 시간에 사용한 함수들을 위주로 사용해보면, 

```{R}
print("hello") # 실행은 Window는, Ctrl + Enter & Mac은 Command + Enter
c(1,2,3,4,5)
paste("Hello","World")
```

`()`안에 데이터를 넣어서 함수를 사용할 수 있습니다. 함수의 결과를 또 다른 변수에 넣어서 사용할 수 있고, 그 변수를 다시 다른 함수의 값으로 넘겨줄 수도 있습니다. 

```{R}
result <-c(1,2,3,4,5,6)
result
```

이 외에도 수 많은 내장함수가 있고, 그 외에도 사람들이 만들어서 공유해놓은 함수들이 많습니다. 그래서 모든 함수를 외우는 것은 불가능합니다. 중요한 것은 내게 필요한 기능을 찾아보는 것입니다. R-CRAN, 구글 검색, 네이버 블로그, 커뮤니티, 책을 통해 필요한 함수찾을 수 있습니다. 이미 존재하는 기능들을 찾아내서 내 필요에 따라 사용하는 것이 더 중요하고, 필요한 능력임을 기억해야 합니다. 

### Packages
`패키지`는 함수들의 모음입니다. 하나의 패키지에는 여러개의 함수로 구성되어 있습니다. R에는 다양한 패키지들이 존재하는데, R의 사용자들이 패키지를 만들어 공유하면 다른 사용자들이 무료로 다운받아 사용할 수 있습니다. 
  
패키지 사용방법은 `설치 -> 로드 -> 사용`의 순서를 거칩니다. 설치는 말그대로 패키지를 내 컴퓨터에 설치하는 작업입니다. 로드는 설치된 패키지를 현재 작업환경에서 사용하기위해 가져오는 작업을 말하고, 로드가 완료되면 패키지에 포함된 함수를 사용할 수 있습니다. 
  
```
install.packages('패키지이름') #설치
library(패키지이름)
?패키지이름 or help(패키지이름) #정보확인
패키지사용
```
  
  
### 마무리
오늘은 함수에 대해 배웠습니다. 함수는 R에서 굉장히 중요한 요소입니다. 모든 기능들이 함수로 이루어져 있다고 봐도 무방합니다. R에서 함수는 크게 내장함수와 직접만든 함수가 있고, 직접만든 함수에서는 내가만든함수와 다른 사람들이 만든 함수가 있습니다. 다른 사람들이 만든 함수는 패키지의 형태로 공유되어 있고, 공유된 패키지를 다운받아서 패키지 안에 있는 함수를 사용할 수 있습니다. 함수와 친해질수록 R을 배우는게 즐거울 것입니다. 
다음 시간에는 R의 데이터 구조에 대해 배울 예정입니다. 데이터 구조까지 배우면 R기초에 대해 대략적으로 다 배운 것입니다. 다음 시간에 만나요. 
  
  
---