---
title: "5.기본데이터구조-스칼라"
author: "Bongus"
date: '2018 7 2 '
output: html_document
---

## 스칼라(Scala)
 R에서 기본 데이터 타입은 벡터(다음에 더 깊게 배울 예정)이다. 벡터는 `a <- 1:5`여러 개의 값으로 구성된 타입의 데이터를 말한다. 벡터에는 한가지 자료형(숫자, 문자)만 저장이 가능하다는 특징이 있다. 벡터 중에서 길이가 1인 벡터를 `스칼라`라고 한다. 즉, 여러개의 값이 아닌 `단일 차원의 값`이 바로 `스칼라`이다.  스칼라로 만들 수 있는 자료형은 `숫자, 문자, NA, NULL, Logical, Factor`가 있다. 
 
### 숫자
```{R}
scala_number <- 1L
print(scala_number)
scala_number2 <- 4.5
print(scala_number2)
```
숫자형 데이터는 스칼라 값으로 가능하다. 숫자에서도 정수, 실수 모두 가능하다. 

### NA(Not Available, 결측치)
```{R}
scala_na <- NA
print(scala_na)
is.na(scala_na)
```
NA는 Not Available을 뜻하는 상수이다. NA는 데이터 값이 없다는 것(결측치)을 의미한다. 결측치는 데이터 입력 중 실수로 값을 입력하지 않은 경우와, 실제로 관찰되지 않은 경우, 적절한 값이 없어서 값이 입력되지 않은 경우가 있다. 데이터 안에 NA값이 있으면 데이터 분석을 할 때 문제가 생길 수 있다. 때문에 데이터를 overview할때 NA값이 있는지 없는지 먼저 확인하는 작업이 반드시 필요하다. R에서는 `is.na()`함수를 통해 확인이 가능하다. 

### NULL
```{R}
scala_null <- NULL
print(scala_null)
is.null(scala_null)
```
NULL은 변수가 초기화 되지 않았을 때 사용한다. NULL은 프로그래밍 상에서 '미정'을 의미한다. 변수에 아직 어떤 값이 들어갈지 알수 없을 경우 NULL로 초기화 하는 경우가 있다. 데이터에 NULL값이 있는지 확인하기 위해서 `is.null()`을 통해 확인이 가능하다. 

### Logical
```{R}
scala_logical <- TRUE
scala_logical2 <- FALSE
scala_logical3 <- TRUE & FALSE
scala_logical4 <- TRUE | FALSE
scala_logical5 <- !TRUE
scala_logical6 <- !FALSE

scala_logical
scala_logical2
scala_logical3
scala_logical4
scala_logical5
scala_logical6
```
logical은 앞서 배웠던 기본자료형에서 참, 거짓 값을 말한다. 논리형 자료형과 and, or, not을 함께 사용해서 scala값을 구성할 수 있다. 

### 문자
```{R}
scala_character <- "문자열"
scala_character2 <- '문자열'

print(scala_character)
print(scala_character2)
```
문자열은 '' or ""로 묶여진 값을 의미한다. 문자열로 구성된 스칼라 역시 만들 수 있다.

### Factor
```
factor(
  data,
  levels,
  ordered
)
data : 표현하고자하는 값(주로 문자열)
levels : 값의 레벨
ordered : T = 순서형, F = 명목형, 기본설정은 명목형(F)이다
```
```{R}
coffee <-factor("small", c("large", "small"), ordered = F)
print(coffee) #어떤 데이터가 들어가있는지 확인
levels(coffee) #범주
is.factor(coffee) # factor여부 확인
```
Factor는 범주형 데이터를 표현하기 위한 데이터 타입이다. 범주형 데이터는 특정 분류 조건으로 나뉘어진 데이터를 말한다. 예를들어 `남자, 여자`, `커피 스몰, 라지` 등이 있다. 범주형 데이터를 만들기 위해서는 구성될 데이터 뿐만 아니라 범주수준(level)까지 입력을 해줘야 한다. 범주형 데이터를 또 나누면, 명목형과 순서형 데이터가 있다. 명목형은 데이터 값들 간의 크기 비교가 불가능한 경우(남녀, 정치성향)를 말하고, 순서형은 순서 비교, 크기 비교가 가능한 데이터(커피 스몰, 라지)를 말한다.  

  
### 마무리
이번 시간에는 스칼라에 대해서 배워봤습니다. 앞서 말씀드렸지만 R에서 기본 데이터 타입은 `벡터`입니다. 스칼라는 벡터의 특수한 형태입니다. 스칼라가 될 수 있는 자료형에는 숫자, 문자, NA, NULL, Logical, Factor가 있음을 배웠습니다. 다음 시간에는 벡터에 대해서 배울 예정입니다. 여기까지 오면서 벡터의 형태를 이미 만나보았기 때문에 어렵지 않게 익힐 수 있는 개념입니다. 다음 시간에 보아요. 
  
  
  ---
