---
title: "6.기본데이터구조-벡터(vector)"
author: "Bongus"
date: '2018 7 3 '
output: html_document
---

## 벡터(Vector)
벡터는 `같은 종류의 자료형으로 구성된 연속된 데이터(sequence of same data element)`입니다. R에서 벡터는 프로그래밍 언어에서 Array(배열)과 비슷합니다. 베열은 데이터와 인덱스(index)로 구성되어 있습니다. 인덱스는 데이터가 저장된 장소의 번호이며, 1부터 시작된다. R에서는 벡터에 저장된 하나의 개별 데이터에 접근해서 데이터를 사용할 수 있고, 배열의 일부를 잘라내서 사용할 수도 있습니다. 
  
R에서 벡터는 데이터의 기본이 되는 자료구조입니다. 벡터를 어떻게 구성하는가에 따라서 뒤에서 배울 `매트릭스 구조`, `데이터 프레임 구조`가 됩니다. 때문에 벡터를 잘 알고가는 것은 굉장히 중요합니다. 

### 벡터만들기
```{R}
vector_number <- c(1,2,3,4,5)
vector_number2 <- 1:5
vector_char <- c("문자","벡터","이렇게","만들어요")


vector_number
vector_number2
vector_char
```
벡터는 기본적으로 하나의 데이터 타입으로 구성됩니다. 벡터를 만들기 위해서는 `c()`함수를 이용합니다. `c()`함수를 이용해서 숫자, 문자로 구성된 벡터를 만들 수 있습니다. 숫자형 벡터를 만들기 위해서 `:`을 사용하기도 합니다. `1:5`은 `1,2,3,4,5`를 변수에 할당합니다. 
  
벡터는 기본적으로 하나의 데이터 형태로 구성되어 있습니다. 다음은 숫자와 문자를 하나의 벡터로 만드는 시도를 해보도록 하겠습니다.
```{R}
vector_numberAndChar <- c(1,"문자",2,"문자")
vector_numberAndChar # ""로 구성된 데이터는 문자를 나타냅니다. 

```
결과처럼 숫자를 입력했지만, 문자로 변해서 출력됨을 확인할 수 있습니다. 
  
`seq()`, `rep()`함수를 사용해서도 벡터를 생성할 수 있다. seq()는 sequence의 약자로 연속된 슷자의 벡터를 만들 수 있고, rep()은 repeat의 약자로 반복된 값의 벡터를 만들 수 있다. 
```
1.
seq(
 시작값(from), 
 끝값(to),
 증가(by)
)

2.
rep(
  반복할 값(data),
  반복횟수(times),
  개별값 반복 횟수(each)
)
```
```{R}
# 1. seq
seq(1, 10) #by를 입력하지 않으면 1이 입력된다
seq(1, 10, 2)
seq(7, 3) # 감소하는 sequence도 가능하다. 

# 2. rep
rep(c(1,2,3), 5) # each를 입력하지 않으면 1이 입력된다.
rep(c(1,2,3), 5, each=2)
```

### 벡터 데이터에 이름붙이기
`names()`라는 함수를 이용하면 벡터 데이터에 이름을 부여할 수 있습니다. 벡므터에 이름이 부여되어 있지 않다면 names(vectorData)는 NULL이라는 값을 반환합니다. 하지만 이름이 부여되어있다면 부여된 이름을 반환합니다. 벡터 데이터에 이름울 부여하기 위해서는 벡터 데이터의 개수만큼의 이름이 필요합니다. 만약 벡터에 5개의 데이터가 있다면, 5개의 이름이 필요합니다. 
```
names(벡터)
```

```{R}
vectorData <- c(1,2,3,4,5)
print(vectorData) 
names(vectorData)

#이름 부여
names(vectorData) <- c("일","이","삼","사","오")
print(vectorData)
names(vectorData) #벡터에 어떤 이름이 부여되어있는지 확인할 수 있습니다. 
```

### 벡터 데이터 접근방법
벡터 데이터에 접근하는 방법은 인덱스를 이용하는 방법과 이름을 이용하는 방법이 있습니다. 벡터에서 하나의 데이터뿐만 아니라 여러개의 데이터에 동시에 접근도 가능합니다. 벡터에서 데이터 접근하는 방식은 R에서 중요한 부분을 차지합니다. 이후 데이터 전처리를 하는 과정에서 반드시 사용되는 개념이니 반드시 숙지하시기 바랍니다.

```
벡터데이터[index] #index번째 데이터에 접근합니다.
벡터데이터[-index] #index번쨰 데이터를 제외한 모든 데이터 접근합니다. 
벡터데이터[시작index:끝index] #시작index와 끝index사이의 모든 데이터에 접근합니다.
벡터데이터[벡터 인덱스 이름] #해당 이름의 데이터에 접근합니다. 
```
```{R}
vector <- c(1,2,3,4,5)
names(vector) <- c("동","해","물","과","백")
print(vector)
print(vector[1]) # 1번쨰 데이터인 1에 접근합니다.
print(vector[-2]) #2번째 데이터인 2를 제외한 모든 데이터에 접근합니다.
print(vector[1:4]) # 1~4번째 데이터에 접근합니다.
print(vector["백"]) # 인덱스 이름이 백인 데이터에 접근합니다. 

print(vector[c(1,3,5)]) # 벡터를 넣어 해당 데이터에 접근도 가능합니다. 1,3,5번째 데이터에 접근합니다. 
print(vector[100]) # 데이터가 들어있지 않은 인덱스를 입력하면 NA를 출력합니다.
```

인덱스를 통해 벡터 데이터에 접근하기 위해서는 벡터에 몇개의 데이터가 들어있는지 확인해야 합니다. 벡터에 몇개의 데이터가 들어있는지 확인하기 위해 `length()`, `NROW()`함수를 사용합니다. length와 NROW를 통해 데이터의 개수(정확히 말하면 데이터의 길이)를 확인할 수 있습니다. 

```{R}
length(vector)
NROW(vector)
```

위에서 선언한 vector에는 1,2,3,4,5 5개의 데이터가 들어있습니다.  length와 NROW의 결과를 확인해보면 5가 나온 것을 확인할 수 있습니다. 

### 벡터 연산
R에서 벡터로 연산이 가능합니다. 벡터와 하나의 숫자, 같은 숫자끼리 벡터의 연산, 그 외에 수학에서 사용하는 집합의 개념을 사용해 벡터 연산이 가능합니다. 

#### 1. 벡터 + 스칼라(하나의 숫자)
```{R}
vectorNumber <- 1:10 # 1,2,3 ..., 10

# vector + scalaNumber
vectorNumber + 1
```

벡터의 모든 값에 스칼라 값이 연산되어서 나오는 것을 확인할 수 있습니다. 

#### 2. 벡터 + 벡터(같은 길이)
```{R}
vectorNumber <- 1:10 # 1,2,3 ..., 10
vectorNumber2 <- 11:20 # 11,12,13 ... 20

# vector + vector
vectorNumber +vectorNumber2 # 1+11, 2 + 12 ... , 10+20
```

각 벡터애서 같은 인덱스에 속하는 값끼리 연산이 이루어 진 것을 확인할 수 있습니다. 

#### 3. 벡터 + 벡터(다른길이)
```{R}
vectorNumber <- 1:10 # 1,2,3 ..., 10
vectorNumber2 <- 1:5 #1,2,3,4,5
vectorNumber3 <- 1:6 #1,2,3,4,5,6

# vector + vector
vectorNumber + vectorNumber2
vectorNumber + vectorNumber3
```
다른 길이의 벡터의 경우, 길이가 긴 벡터가, 길이가 짧은 벡터의 배수인 경우 짧은 벡터가 끝나는 지점에서 다시 처음부터 한번 더 더해지는 것을 확인할 수 있습니다.. 
  
길이가 긴 벡터가 길이가 짧은 벡터의 배수가 아닌 경우 경고문이 뜨는 것을 확인할 수 있고, 긴 데이터의 끝에 도달할 때까지 반복해서 더해지는 것을 확인할 수 있습니다.

#### 4. 집합연산
```
identical() => 두개의 객체가 동일한지 판단
union() => 합집합
intersect() => 교집합
setdiff() => 차집합
setequal() => 같은 집합인지 판단 

```
setequal vs identical
[link](https://stackoverflow.com/questions/42777625/what-is-the-difference-between-setequala-b-and-identicala-b-in-r)
```{R}
a <- c(1,2,3)
b <- c(1,2,3,4)

identical(a,b)
union(a,b)
intersect(a,b)
setdiff(a,b) # a - b
setdiff(b,a) # b - a
setequal(a,b)
```
  

이번 시간에는 벡터에 대해서 배웠습니다. 다소 지루하고, 어려운 내용이지만 굉장히 중요한 내용입니다. 특히 데이터에 대한 이해, 데이터 접근, 데이터 전처리 과정을 이해하기 위해 반듯 알아야하는 내용들을 다루었으니 꼼꼼히 읽어보시고, 외부 자료도 참고하며 학습하시기 바랍니다. 다음시간에는 리스트에 대해서 학습하도록 하겠습니다. 

  
  
---