---
title: "8.기본데이터구조-메트릭스"
author: "Bongus"
date: '2018 7 4 '
output: html_document
---

## 행렬(Matrix)
행렬은 데이터가 행(row)과 열(column)으로 저장된 구조입니다. 벡터와 마찬가지로 행렬에는 하나의 자료형으로만 구성해야 합니다. 즉, 1열은 숫자 2열은 문자형 같은 형태는 불가능하다. 모든 행과 열이 숫자이거나 문자로 구성되어야 한다. 행렬을 앞에 배운 개념들을 이용해 설명하면 행렬은 길이가 같은 벡터를 합쳐놓은 것입니다. 때문에 이미 만들어진 벡터를 통해서도 행렬을 만들 수 있습니다. 

행/열|열1|열2
--|--|--
행1|행1,열1|행1,열2
행2|행2,열1|행2,열2
행3|행2,열1|행3,열2

### 행렬 만들기
행렬은 `matrix()`함수를 사용해서 만들 수 있다.
```
matrix(
  data,
  nrow 행의 수
  ncol, 열의 수
  byrow=FALSE, 열 우선으로 데이터를 나열할 것인지, 행 우선으로 데잍를 나열할 것인지
  dimnames=NULL 행과 열에 입력한 이름
)
```
```{R}
data <- c(1,2,3,4,5,6,7,8,9)
mat1 <-matrix(data, nrow=3)
print(mat1)
mat2 <- matrix(data, nrow=3, ncol=3, byrow=T, dimnames=list(c("행1","행2","행3"), c("열1","열2","열3")))
print(mat2)

dimnames(mat1)
dimnames(mat2)

rownames(mat1)
colnames(mat1)

rownames(mat2)
colnames(mat2)
```

행과 열에 이름을 부여하고 싶으면 dimnames에 list의 형태로 행,열의 이름을 지정해야 합니다. 리스트의 첫번째 데이터는 '행의 이름', 두번째 데이터는 '열의 이름'을 입력하면 됩니다. dimnames를 matrix함수 외부에서 사용하면 만들어진 행렬의 행과 열의 이름을 확인할 수 있습니다. 이름이 지정되어있지 않으면 `NULL`값이 반환되고, 이름이 정해져 있다면 행과 열의 이름이 반환됩니다. rownames()와 colnames()를 사용하면 행과 열에 어떤 이름이 부여되어있는지 확인할 수 있습니다. 이름이 부여되어 있지 않으면 NULL값이 반환됩니다. 

### 행렬 데이터 접근
앞서 배운 벡터처럼 행렬의 데이터에 접근이 가능합니다. 행렬로 만들어진 데이터에 접근하기 위해서는 인덱스 또는 행과 열의 이름을 이용하면 됩니다. 

```
행렬데이터[행인덱스, ] 행 전체
행렬데이터[, 열인덱스] 열 전체
행렬데이터[행인덱스, 열인덱스] 행,열 데이터
행렬데이터["행이름", "열이름"] 행,열 데이터
```

```{R}
data <- 1:9
mat <- matrix(data, nrow=3, byrow=TRUE)

print(mat)
print(mat[1,]) #1행 전체에 접근 가능
print(mat[,2]) #2열 전체에 접근 가능
print(mat[1,1]) #1행 1열에 접근 가능
print(mat[2,3]) #2행 3열에 접근 가능
print(mat[-3,]) #-인덱스 값을 입력하면, 해당 인덱스의 데이터를 제외한 값에 접근 가능
print(mat[c(1,3),c(1,3)]) # 1,3행, 1,3열에 접근 가능하다
```

### 행열 연산
```
행렬 + 스칼라
행렬 + 행렬
행렬 %*% 행렬 = 수학에서의 행렬 곱
```

```{R}
data <- 1:9
data2 <-rep(10,9) 

mat1 <- matrix(data, nrow = 3, ncol = 3)
mat2 <- matrix(data2, nrow = 3, ncol = 3)
mat3 <- matrix(data, nrow = 2)
# matrix + scala
mat1 + 10 
mat1 - 10 
mat1 * 10 
mat1 / 10 
```
행렬과 스칼라값(하나의 데이터)를 더하면 행렬의 모든 값에 스칼라 값이 더해지는 것을 확인할 수 있다. 빼기, 곱하기, 나누기 모두 마찬가지임을 확인할 수 있다.

  
```{R}
mat1 + mat2
mat1 - mat2
mat1 * mat2
mat1 / mat2

#mat1 + mat3 연산되는 행열의 행과 열의 수가 다르면 연산이 불가능하다.
```
행렬과 행렬을 더하면 인덱스 값이 같은 데이터끼리 연산이 이루어집니다. 빼기, 곱하기, 나누기 모두 마찬가지의 결과를 확인할 수 있습니다. 수학에서 행렬곱을 수행하기 위해서는 `*`이 아니라 `%*%`을 통해 수학적 행렬곱을 수행할 수 있습니다. 
```{R}
#일반 곱연산
mat1 * mat2
#행렬 곱연산
mat1 %*% mat2
```
t()와 solve()함수를 이용하면, 각각 전치행렬과 역행렬을 구할 수 있습니다. 
```{R}
mat <- matrix(1:4, nrow=2)
print(mat)
mat #일반 행렬
t(mat) #전치 행렬
solve(mat) #역행렬
```

nrow(), ncol(), dim() 함수를 이용하면 행과 열이 몇개가 있는지 확인 가능합니다.
```{R}
print(mat)
nrow(mat)  #행의 개수
ncol(mat) #열의 개수
dim(mat) #행렬의 개수

print(mat)
dim(mat) <- c(1,4) #dim함수를 사용해서 행렬을 구하고, 행렬의 행과 열의 차원을 바꿀 수 있습니다. 
print(mat)
```
  
### 마무리
행렬을 이용하면 수학적 연산을 빠르게 수행할 수 있습니다. 다음에 배울 데이터 프레임에 비하면 활용도가 떨어지는 것처럼 보이지만 머신러닝이나 인공지능 영역에서는 연산을 빠르게 수행하기 위해 행렬의 개념을 사용하고 있습니다. 또한 데이터 전처리 과정에서 많이 사용하는 apply()함수가 있는데, apply함수를 가지고 행렬 데이터를 가공할 수 있습니다. R에서 행렬은 기본이 되는 데이터 구조이니 꼼꼼히 학습하도록 합시다! 다음 시간에는 데이터프레임을 배워보도록 하겠습니다. 

  
  
  
  ---
